Class {
	#name : 'CardEffect',
	#superclass : 'Object',
	#category : 'IngSoft2-Model-CardEffect',
	#package : 'IngSoft2-Model',
	#tag : 'CardEffect'
}

{ #category : 'actions' }
CardEffect >> applyMercenaryEffectFor: aShip in: aListMercenaries from: cardOwner [
]

{ #category : 'actions' }
CardEffect >> applyPlayedEffectIn: aGame from: owner to: aTargetShip [
]

{ #category : 'actions' }
CardEffect >> applyThrowEffectFor: aShip [
	^ 0
	
]

{ #category : 'as yet unclassified' }
CardEffect >> checkForTargetRequirementsFor: aTargetShip whoPlayed: aTargetCardName [

]

{ #category : 'as yet unclassified' }
CardEffect >> checkForTurnRequierementwhen: aShip playsACardDuringTheTurnOf: anotherShip [
]
